### ISSUE TITLE
Upgrade to yew 0.19.x

### ISSUE THREAD

**Issue by ctron** [siku2/rust-monaco#11]
It would be great if the component could be upgraded to work with Yew 0.19

**Comment by ctron** [comment]
@siku2 Could you create a new release with this change?

**Comment by siku2** [comment]
> @siku2 Could you create a new release with this change?

Sure thing.
Please remind me again if I haven't gotten to it by Saturday.

**Comment by siku2** [comment]
> @siku2 Could you create a new release with this change?

Alright, 0.3.0 is live!
