### ISSUE TITLE
Example of hooking up `on_did_change_content`?

### ISSUE THREAD

**Issue by max-sixty** [siku2/rust-monaco#19]
Hi @siku2 !

We're trying to use this library in https://github.com/max-sixty/prql/pull/304. I'm completely new to web development, and so I'm sure I'm missing something obvious, but I'm struggling to get the `on_did_change_content` event to allow a function to run over the text on each change.

Would you have any examples of this working? I've used https://github.com/siku2/rust-monaco/blob/master/examples/yew/src/lib.rs to get started, which was great, but didn't have any events. I also tried searched GitHub for any examples.

Thanks a lot in advance.

**Comment by siku2** [comment]
Hey, thanks for giving this library a shot!

Here's a modified version of the example which uses the on_did_change_content callback and logs the events to the console using `gloo-console`:
```rust
use monaco::{
    api::{CodeEditorOptions, DisposableClosure, TextModel},
    sys::editor::{BuiltinTheme, IModelContentChangedEvent},
    yew::CodeEditor,
};
use std::rc::Rc;
use wasm_bindgen::prelude::*;
use yew::{html, Component, Context, Html};

const CONTENT: &str = include_str!("lib.rs");

struct App {
    options: Rc<CodeEditorOptions>,
    model: TextModel,
    // we need to prevent this from being dropped for the listener to stay active
    _listener: DisposableClosure<dyn FnMut(IModelContentChangedEvent)>,
}
impl Component for App {
    type Message = ();
    type Properties = ();

    fn create(_context: &Context<Self>) -> Self {
        // as soon as you're doing anything more advanced than just displaying text, you
        // should use the `TextModel` API (monaco uses it for everything internally)
        let model = TextModel::create(CONTENT, Some("rust"), None).unwrap();
        let listener = model.on_did_change_content(|ev| gloo_console::log!(ev));

        Self {
            options: Rc::new(CodeEditorOptions::default().with_builtin_theme(BuiltinTheme::VsDark)),
            model,
            _listener: listener,
        }
    }

    fn changed(&mut self, _context: &Context<Self>) -> bool {
        false
    }

    fn view(&self, _context: &Context<Self>) -> Html {
        html! {
            <CodeEditor options={ Rc::clone(&self.options) } model={ self.model.clone() } />
        }
    }
}
```

I think you were pretty close at one point with your code but it looks like you forgot to keep the `DisposableClosure` alive.

Btw, this library contains fully complete bindings to the monaco js API, but the high level Rust API is somewhat lacking. I'm not actively using this library right now so I haven't had to chance to continue working on it. If you do end up using this crate, please consider pointing out the rough edges and contributing changes.
Speaking of changes, you don't necessarily have to make the move from `sycamore` to `yew`. The yew component is a fairly straight-forward abstraction over [`CodeEditor::create`](https://docs.rs/monaco/latest/monaco/api/struct.CodeEditor.html#method.create).

**Comment by max-sixty** [comment]
Thanks a lot @siku2 !

I'm a bit closer indeed! I haven't managed to get the thing updating on every change. I see the log messages, but I'm not sure how to connect the `listener` so that the component recalculates — it seems quite unlike the usual `onclick` events in the classic Yew examples. I've posted my latest code.

If you see this and have the answer to hand, that would be great. Either way, I very much appreciate your help. To the extent we successfully publish this, I'd be happy to contribute upstream.

**Comment by siku2** [comment]
I think what you need is this:
```rust
// create the callback like you would normally
let callback = context.link().callback(Msg::ModelContentChanged);
// move the callback into the closure and trigger it manually
let listener = model.on_did_change_content(move |ev| callback.emit(ev));
```

<details><summary>Here's the full example again if you need it</summary>
<p>

```rust
enum Msg {
    ModelContentChanged(IModelContentChangedEvent),
}

struct App {
    options: Rc<CodeEditorOptions>,
    model: TextModel,
    _listener: DisposableClosure<dyn FnMut(IModelContentChangedEvent)>,
}
impl Component for App {
    type Message = Msg;
    type Properties = ();

    fn create(context: &Context<Self>) -> Self {
        let model = TextModel::create(CONTENT, Some("rust"), None).unwrap();

        // create the callback like you would normally
        let callback = context.link().callback(Msg::ModelContentChanged);
        // move the callback into the closure and trigger it manually
        let listener = model.on_did_change_content(move |ev| callback.emit(ev));

        Self {
            options: Rc::new(CodeEditorOptions::default().with_builtin_theme(BuiltinTheme::VsDark)),
            model,
            _listener: listener,
        }
    }

    fn changed(&mut self, _context: &Context<Self>) -> bool {
        false
    }

    fn view(&self, _context: &Context<Self>) -> Html {
        html! {
            <CodeEditor options={ Rc::clone(&self.options) } model={ self.model.clone() } />
        }
    }

    fn update(&mut self, _context: &Context<Self>, msg: Msg) -> bool {
        match msg {
            Msg::ModelContentChanged(ev) => {
                gloo_console::log!(ev);
                true
            }
        }
    }
}
```

</p>
</details>


Also happy to provide code snippets catered to your use case if you elaborate what you want to do.

**Comment by max-sixty** [comment]
Amazing! It works. I was deeeep into [creating custom events](https://yew.rs/docs/concepts/html/events#using-gloo-concise)...

Thanks a lot! 

I'll close this, push my changes, and hopefully iterate on it over the coming days & weeks.
