### ISSUE TITLE
Update bindings

### ISSUE THREAD

**Issue by SpanishPear** [siku2/rust-monaco#28]
There have been some updates to the public API - for example `0.34` introduced `IEditor.createDecorationsCollection` (which I can't find a binding for). I don't really need this, but was curious. 

Is this something that is done automatically via a script of sorts, or does it need to be done manually? 

Would be good to add what version number of `monaco` this is accurate bindings to. 

EDIT: seems like I can't read - there's the ts2rs folder.. :P

**Comment by siku2** [comment]
Let's coordinate these efforts in the #41
