### ISSUE TITLE
Dynamic auto size

### ISSUE THREAD

**Issue by oovm** [siku2/rust-monaco#3]
The size of the current editor is fixed, but I want to adapt to the container size.

Here is a solution, which is to listen to the resize event: https://github.com/microsoft/monaco-editor/issues/28#issuecomment-263084405

How can I do this layout reset in yew?

**Comment by siku2** [comment]
There is no high-level API for the editor layout yet, but you can easily call the [`ICodeEditor::layout`](https://docs.rs/monaco/0.1.0/monaco/sys/editor/struct.ICodeEditor.html#method.layout) method directly:

```rs
// assuming your `CodeEditor` is called `editor`:
let editor: CodeEditor;

// as_ref() to get access to the underlying js bindings
// passing `None` as the dimension so the editor automatically determines the size based on the parent container 
editor.as_ref().layout(None);
```

Now you just need to do this whenever you want the editor to resize. For instance, you could use Yew's [`ResizeService`](https://docs.rs/yew/0.17.4/yew/services/resize/index.html).


You could also use the [`automatic_layout`](https://docs.rs/monaco/0.1.0/monaco/sys/editor/struct.IEditorConstructionOptions.html#method.set_automatic_layout) property, but as described in the issue you linked, that's not very efficient.

**Comment by siku2** [comment]
Btw, I totally think this should be part of the high-level API. The reason it's not in there is simply because the high-level API is still under development.

**Comment by oovm** [comment]
It really needs to be corrected, this interface is not consistent

`CodeEditorOptions {dimension: _}` using `IDimension(usize, usize)`

while `editor.as_ref().layout(_)` using `&IDimension(f64, f64)`

**Comment by siku2** [comment]
> It really needs to be corrected, this interface is not consistent
> 
> `CodeEditorOptions {dimension: _}` using `IDimension(usize, usize)`
> 
> while `editor.as_ref().layout(_)` using `&IDimension(f64, f64)`

Where did you get that from? It should always be `f64`.
