### ISSUE TITLE
Creating `IMarkerData` instances

### ISSUE THREAD

**Issue by ctron** [siku2/rust-monaco#35]
I am trying to set markers. To my understanding I need to create an `IMarkerData` instance. However, I can't see any constructor method, like `new`.

**Comment by ctron** [comment]
I am running into the same issue with other types as well, like `LanguageConfiguration` and `CommentRule`, to name a few.

They seem to "extend" on `Object`, but not allow to create an empty/default instance.

Maybe you can point me into the right direction, I might be able to come up with a PR.

**Comment by siku2** [comment]
That's the correct way to do it, yes. I just added a convenience constructor for the various types I could think of.

**Comment by ctron** [comment]
I guess this can be closed now.
