### ISSUE TITLE
Creating a new release for yew 0.20

### ISSUE THREAD

**Issue by ctron** [siku2/rust-monaco#36]
The main branch has support for Yew 0.20, but that isn't released yet from what I saw.

It would be great if you could do another release, so that it can be used without using a git dependency.

**Comment by siku2** [comment]
Yes, I need to find some time to do it, but please don't hesitate to ping me again if I forget.

I would love to add you as a maintainer as well if you're interested.

**Comment by Ddystopia** [comment]
@siku2 Hello, is there any progress?

**Comment by holly-hacker** [comment]
Considering you asked to be pinged if you forgot, @siku2 :)

**Comment by siku2** [comment]
After a frankly embarrassing amount of time, I finally published a new version.
Thanks @Ddystopia and @holly-hacker for reminding me, although it still took a couple of months for me to get to it
