### ISSUE TITLE
How to add addition options to construct editor

### ISSUE THREAD

**Issue by oovm** [siku2/rust-monaco#4]
How to initialize an editor using [IEditorOptions](https://docs.rs/monaco/0.1.0/monaco/sys/editor/struct.IEditorOptions.html) or [IEditorConstructionOptions](https://docs.rs/monaco/0.1.0/monaco/sys/editor/struct.IEditorConstructionOptions.html)?

**Comment by siku2** [comment]
Use the [create_with_sys_options](https://docs.rs/monaco/0.1.0/monaco/api/struct.CodeEditor.html#method.create_with_sys_options)
