### ISSUE TITLE
Github - Crates.io disparity?

### ISSUE THREAD

**Issue by PawelPerek** [siku2/rust-monaco#42]
Hi there, I'm trying to integrate monaco into my leptos project and so far API impressions were excellent, but lately I found a weird disparity. I would like to use automatic_layout feature, so the editor would automatically fit the parent container and I see that on Github there is a `CodeEditorOptions::automatic_layout`  field (https://github.com/siku2/rust-monaco/blob/master/src/api/editor.rs), but weirdly enough when I pull it from crates.io, the `CodeEditorOptions` has all the fields besides this one. 
I see that entry in docs.rs also doesn't list this field as an option https://docs.rs/monaco/0.3.0/monaco/api/struct.CodeEditorOptions.html. It's a weird disparity since both github and crates.io variants has 0.3.0 version identifier.

**Comment by siku2** [comment]
See #36, which should now finally be fixed :)
