### ISSUE TITLE
Pulling value from CodeEditors textmodel

### ISSUE THREAD

**Issue by wylited** [siku2/rust-monaco#43]
I want to create a submit button for the code editor and so far I have this.
```rust
 <CodeEditor classes={"full-height"} options={
                            CodeEditorOptions::default()
                                .with_language("rust".to_owned())
                                .with_value(self.cell_states[&self.selected_state].get_value())
                                .with_builtin_theme(BuiltinTheme::VsDark)
                                .with_automatic_layout(true)
                                .to_sys_options()
                        } />
                        <br />
                        <button class="game-button" onclick={ctx.link().callback(|_| Msg::Code("".to_string()))}>{ "Submit" }</button>
```
I want the user to be able to use the editor and then once they made significant changes, hit submit and have the code be saved in into the self.cell_states[&self.selected_state] hash map. However, I don't know how to access the user edited TextModel once it's been edited and how to update it.
It's also ok if it saves without needing to press submit, I just want to know how to store it.

**Comment by b0x-Cub3d** [comment]
The simplest approach is to create a textmodel property for your code editor to keep track of whether it's being changed. Then, you can create a component with the code editor and its textmodel. With the textmodel initialized, you should be able to get what's inside via `.get_value()`. 

I should note that you have to clone the textmodel as you are passing it between callbacks, as shown [here](https://github.com/siku2/rust-monaco/blob/main/examples/yew_events_external/src/main.rs#L57).

**Comment by wylited** [comment]
Sorry to further disturb you.
When using `use_state_eq(|| TextModel::create(&random_string(), Some("rust"), None).unwrap());`
the code works perfectly fine in the example and I can play around with the implementation.
But in my own project where I copy the exact same line, I get this error:
![image](https://github.com/siku2/rust-monaco/assets/44154103/8df89218-f3de-4dcd-aa21-a077e5f123d7)

Because the function use_state_eq returns an opaque type T.
I'm really confused why this is and would greatly appreciate it if you could point me in the right direction.
Should I be using https://docs.rs/yew/latest/yew/functional/fn.use_state_eq.html or another one.

thanks alot.

**Comment by wylited** [comment]
nevermind this the solution was alot easier than i thought.
```
<CodeEditor classes={"full-height"} options={
                            CodeEditorOptions::default()
                                .with_language("rust".to_owned())
>>                              .with_model(self.cell_states[&self.selected_state].clone())
                                .with_builtin_theme(BuiltinTheme::VsDark)
                                .with_automatic_layout(true)
                                .to_sys_options()
                        } />
                        <br />
                        <button class="game-button" onclick={ctx.link().callback(|_| Msg::Code("".to_string()))}>{ "Submit" }</button>
                        ```

thanks alot for the help regardless
