### ISSUE TITLE
Unable to use IStandaloneEditorConstructionOptions with Yew component

### ISSUE THREAD

**Issue by ctron** [siku2/rust-monaco#5]
It looks to me as if it is not possible to use the `IStandaloneEditorConstructionOptions` (from .to_sys_options()) with the Yew component.

However, I would like to disable overscrolling by setting `scrollBeyondLastLine: false`.

**Comment by siku2** [comment]
That's very much possible. I wouldn't mind if it were possible to pass a `IStandaloneEditorConstructionOptions` to the component. Alternatively, the existing high level options could be extended to allow for this to be configured.
