### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ctron** [siku2/rust-monaco#6]
I noticed that the master branch has some more changes for Yew, which allows one to change the content through an update.

I tested this from the main branch, but I was hoping for a new release. Are there any plans?

**Comment by siku2** [comment]
Sure, I can release a new one. Might want to wait for #5 though.

**Comment by ctron** [comment]
Thanks for merging #7 and fixing #5! Maybe now is the time for a new release? :)

**Comment by siku2** [comment]
> Thanks for merging #7 and fixing #5! Maybe now is the time for a new release? :)

You're right, I'll try to get it done soon

**Comment by siku2** [comment]
Done!
