### ISSUE TITLE
Setting function to `line_numbers` editor option

### ISSUE THREAD

**Issue by wkordalski** [siku2/rust-monaco#9]
Monaco editor allows for passing functions to `line_numebers` editor option.

https://github.com/siku2/rust-monaco/blob/1412b80817123f6e687c01e623894905e1913e5d/ts2rs/monaco.d.ts#L3521-L3526

Unfortunatelly it is translated to Rust in a wrong way:

https://github.com/siku2/rust-monaco/blob/1412b80817123f6e687c01e623894905e1913e5d/src/sys/editor.rs#L481-L489

I've expanded the macros and implemented `LineNumbersType` so that is accepts also `js_sys::Function` in https://github.com/wkordalski/rust-monaco/commit/405534517af4b43ab6517b4ed623e5996b2ec096

---

However, probably the bindings generator should be fixed?
I would appreciate some instructions on how to run the bindings generator, when it should be done, and whether some additional steps are needed or not.

**Comment by siku2** [comment]
I made the generator to help with the initial translation, I never expected it to provide proper bindings.
If you're interested in improving the generator that would be great, obviously, but I'm perfectly fine with manually fixing the bindings.
A PR with your fix would be appreciated too!

**Comment by wkordalski** [comment]
Fixed by https://github.com/siku2/rust-monaco/pull/10
